// components/AddModal.tsx

import React, { useState } from 'react';
import { CATEGORIES, TransactionType } from '../types';
import { X, Check } from 'lucide-react';
import { clsx } from 'clsx';
import { v4 as uuidv4 } from 'uuid';

interface AddModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAdd: (transaction: any) => void;
}

export const AddModal: React.FC<AddModalProps> = ({ isOpen, onClose, onAdd }) => {
  const [type, setType] = useState<TransactionType>('expense');
  const [amount, setAmount] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('food');

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!amount) return;

    onAdd({
      id: uuidv4(),
      amount: parseFloat(amount),
      description,
      category: type === 'income' ? 'income' : category,
      type,
      date: new Date().toISOString(),
    });

    // Reset
    setAmount('');
    setDescription('');
    setCategory('food');
    setType('expense');
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-fade-in">
      <div className="bg-white w-full max-w-md rounded-3xl p-6 shadow-2xl animate-slide-up">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-bold text-slate-900">Add Transaction</h2>
          <button onClick={onClose} className="p-2 bg-slate-100 rounded-full hover:bg-slate-200 transition">
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-2 p-1 bg-slate-100 rounded-xl mb-6">
            <button
              type="button"
              onClick={() => setType('expense')}
              className={clsx(
                "py-2 px-4 rounded-lg text-sm font-semibold transition-all",
                type === 'expense' ? "bg-white text-rose-600 shadow-sm" : "text-slate-500 hover:text-slate-700"
              )}
            >
              Expense
            </button>
            <button
              type="button"
              onClick={() => setType('income')}
              className={clsx(
                "py-2 px-4 rounded-lg text-sm font-semibold transition-all",
                type === 'income' ? "bg-white text-emerald-600 shadow-sm" : "text-slate-500 hover:text-slate-700"
              )}
            >
              Income
            </button>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Amount</label>
            <div className="relative">
              <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold text-lg">$</span>
              <input
                type="number"
                step="0.01"
                required
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                className="w-full bg-slate-50 border border-slate-200 rounded-xl py-3 pl-10 pr-4 text-lg font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition"
                placeholder="0.00"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Description</label>
            <input
              type="text"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 rounded-xl py-3 px-4 text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition"
              placeholder="What was this for?"
            />
          </div>

          {type === 'expense' && (
            <div>
              <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Category</label>
              <div className="grid grid-cols-4 gap-2">
                {CATEGORIES.filter(c => c.id !== 'income').map((cat) => (
                  <button
                    key={cat.id}
                    type="button"
                    onClick={() => setCategory(cat.id)}
                    className={clsx(
                      "flex flex-col items-center justify-center p-2 rounded-xl border transition-all text-xs",
                      category === cat.id 
                        ? "border-blue-500 bg-blue-50 text-blue-700" 
                        : "border-slate-100 bg-white text-slate-500 hover:border-slate-300"
                    )}
                  >
                    <div 
                      className="w-8 h-8 rounded-full mb-1 flex items-center justify-center text-white"
                      style={{ backgroundColor: cat.color }}
                    >
                      <span className="text-[10px] font-bold">{cat.name[0]}</span>
                    </div>
                    <span className="truncate w-full text-center">{cat.name}</span>
                  </button>
                ))}
              </div>
            </div>
          )}

          <button
            type="submit"
            className="w-full bg-slate-900 text-white font-bold py-4 rounded-xl shadow-lg shadow-slate-200 active:scale-[0.98] transition-all flex items-center justify-center gap-2 mt-4"
          >
            <Check size={20} /> Save Transaction
          </button>
        </form>
      </div>
    </div>
  );
};

// src/app/components/add-modal/add-modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule } from 'lucide-angular';
import { TransactionType, Category } from '../../models/transaction.model';

@Component({
  selector: 'app-add-modal',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  template: `
    <div *ngIf="isOpen" class="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center p-0 sm:p-4">
      <div class="bg-slate-900 w-full max-w-md rounded-t-2xl sm:rounded-2xl border-t sm:border border-slate-700 p-6 animate-slideUp">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-xl font-bold text-white">New Transaction</h2>
          <button (click)="onClose.emit()" class="p-2 hover:bg-slate-800 rounded-full text-slate-400">
            <lucide-icon name="x" [size]="24"></lucide-icon>
          </button>
        </div>

        <form (ngSubmit)="handleSubmit()" class="space-y-5">
          <!-- Toggle Type -->
          <div class="flex bg-slate-800 p-1 rounded-lg">
            <button
              type="button"
              (click)="type = 'EXPENSE'"
              class="flex-1 py-2 rounded-md text-sm font-medium transition-colors"
              [class]="type === 'EXPENSE' ? 'bg-red-500/20 text-red-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'"
            >
              Expense
            </button>
            <button
              type="button"
              (click)="type = 'INCOME'"
              class="flex-1 py-2 rounded-md text-sm font-medium transition-colors"
              [class]="type === 'INCOME' ? 'bg-emerald-500/20 text-emerald-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'"
            >
              Income
            </button>
          </div>

          <div>
            <label class="block text-xs font-medium text-slate-400 mb-1">Amount</label>
            <div class="relative">
              <span class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 font-bold">$</span>
              <input
                type="number"
                step="0.01"
                required
                [(ngModel)]="amount"
                name="amount"
                class="w-full bg-slate-800 border border-slate-700 rounded-xl py-3 pl-8 pr-4 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 placeholder-slate-500 text-lg font-semibold"
                placeholder="0.00"
              />
            </div>
          </div>

          <div>
            <label class="block text-xs font-medium text-slate-400 mb-1">Description</label>
            <input
              type="text"
              required
              [(ngModel)]="description"
              name="description"
              class="w-full bg-slate-800 border border-slate-700 rounded-xl py-3 px-4 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 placeholder-slate-500"
              placeholder="What is this for?"
            />
          </div>

          <div>
            <label class="block text-xs font-medium text-slate-400 mb-1">Category</label>
            <select
              [(ngModel)]="category"
              name="category"
              class="w-full bg-slate-800 border border-slate-700 rounded-xl py-3 px-4 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 appearance-none"
            >
              <option *ngFor="let cat of categories" [value]="cat">{{ cat }}</option>
            </select>
          </div>

          <button
            type="submit"
            class="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-4 rounded-xl flex items-center justify-center gap-2 mt-4 transition-colors"
          >
            <lucide-icon name="check" [size]="20"></lucide-icon>
            Save Transaction
          </button>
        </form>
      </div>
    </div>
  `
})
export class AddModalComponent {
  @Input() isOpen = false;
  @Output() onClose = new EventEmitter<void>();
  @Output() onAdd = new EventEmitter<{amount: number, description: string, type: TransactionType, category: Category}>();

  amount: string = '';
  description: string = '';
  type: string = 'EXPENSE'; // String matching Enum key
  category: Category = Category.FOOD;
  
  categories = Object.values(Category);

  handleSubmit() {
    if (!this.amount || !this.description) return;
    
    this.onAdd.emit({
      amount: parseFloat(this.amount),
      description: this.description,
      type: this.type as TransactionType,
      category: this.category
    });

    // Reset
    this.amount = '';
    this.description = '';
    this.onClose.emit();
  }
}
