// src/app/components/transaction-item/transaction-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { Transaction, TransactionType, CATEGORY_COLORS } from '../../models/transaction.model';

@Component({
  selector: 'app-transaction-item',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <div class="flex items-center justify-between p-4 bg-slate-800 rounded-xl mb-3 shadow-sm border border-slate-700/50 hover:border-slate-600 transition-colors group">
      <div class="flex items-center gap-4">
        <div 
          class="w-10 h-10 rounded-full flex items-center justify-center bg-slate-900"
          [style.color]="getCategoryColor()"
        >
          <lucide-icon [name]="isExpense ? 'arrow-up-right' : 'arrow-down-left'" [size]="20"></lucide-icon>
        </div>
        <div>
          <h3 class="text-sm font-semibold text-slate-100">{{ item.description }}</h3>
          <p class="text-xs text-slate-400">{{ item.category }} • {{ item.date | date:'MMM d' }}</p>
        </div>
      </div>
      <div class="flex items-center gap-3">
        <span class="font-bold text-sm" [class.text-red-400]="isExpense" [class.text-emerald-400]="!isExpense">
          {{ isExpense ? '-' : '+' }}${{ item.amount | number:'1.2-2' }}
        </span>
        <button 
          (click)="onDelete.emit(item.id)"
          class="text-slate-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity p-1"
        >
          <lucide-icon name="trash-2" [size]="16"></lucide-icon>
        </button>
      </div>
    </div>
  `
})
export class TransactionItemComponent {
  @Input({ required: true }) item!: Transaction;
  @Output() onDelete = new EventEmitter<string>();

  get isExpense(): boolean {
    return this.item?.type === TransactionType.EXPENSE;
  }

  getCategoryColor(): string {
    return this.item ? CATEGORY_COLORS[this.item.category] : '#fff';
  }
}

// src/components/TransactionItem.tsx
import React from 'react';
import { Transaction, TransactionType } from '../types';
import { CATEGORY_COLORS } from '../constants';
import { ArrowDownLeft, ArrowUpRight, Trash2 } from 'lucide-react';

interface Props {
  transaction: Transaction;
  onDelete: (id: string) => void;
}

const TransactionItem: React.FC<Props> = ({ transaction, onDelete }) => {
  const isExpense = transaction.type === TransactionType.EXPENSE;
  const dateObj = new Date(transaction.date);
  const formattedDate = dateObj.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });

  return (
    <div className="flex items-center justify-between p-4 bg-slate-800 rounded-xl mb-3 shadow-sm border border-slate-700/50 hover:border-slate-600 transition-colors group">
      <div className="flex items-center gap-4">
        <div 
          className="w-10 h-10 rounded-full flex items-center justify-center bg-slate-900"
          style={{ color: CATEGORY_COLORS[transaction.category] }}
        >
          {isExpense ? <ArrowUpRight size={20} /> : <ArrowDownLeft size={20} />}
        </div>
        <div>
          <h3 className="text-sm font-semibold text-slate-100">{transaction.description}</h3>
          <p className="text-xs text-slate-400">{transaction.category} • {formattedDate}</p>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <span className={`font-bold text-sm ${isExpense ? 'text-red-400' : 'text-emerald-400'}`}>
          {isExpense ? '-' : '+'}${transaction.amount.toFixed(2)}
        </span>
        <button 
          onClick={() => onDelete(transaction.id)}
          className="text-slate-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity p-1"
        >
          <Trash2 size={16} />
        </button>
      </div>
    </div>
  );
};

export default TransactionItem;
